/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 2000

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 10000

    subsystem_namespace: /hardware_interface
    required_subsystem_nodes: ['']
    unmanaged_required_nodes: ['']
    excluded_namespace_nodes:
      - /hardware_interface/carla_lidar_driver
      - /hardware_interface/carla_gnss_driver
    ros1_required_drivers:
      - /hardware_interface/carla_driver
    ros1_camera_drivers:
      - /hardware_interface/carla_camera_driver
    full_subsystem_required: false


    # Int: The time allocated for system startup in seconds
    startup_duration: 30

    # Double: The timeout threshold for essential drivers in ms
    required_driver_timeout: 30000.0