/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 2000

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 10000

    subsystem_namespace: /guidance
    required_subsystem_nodes: ['']
    unmanaged_required_nodes: [''] # TODO add the controller driver once it is integrated with ROS2
    full_subsystem_required: true
    required_plugins:
      - /guidance/plugins/route_following_plugin
      - /guidance/plugins/pure_pursuit_wrapper
      - /guidance/plugins/inlanecruising_plugin
      - /guidance/plugins/cooperative_lanechange
    auto_activated_plugins:
      - /guidance/plugins/lci_strategic_plugin
      - /guidance/plugins/intersection_transit_maneuvering
      - /guidance/plugins/light_controlled_intersection_tactical_plugin
      - /guidance/plugins/stop_and_wait_plugin
      - /guidance/plugins/sci_strategic_plugin
      - /guidance/plugins/stop_controlled_intersection_tactical_plugin
      - /guidance/plugins/platoon_control_ihp
      - /guidance/plugins/platoon_strategic_ihp_node
      - /guidance/plugins/platooning_tactical_plugin_node
      - /guidance/plugins/yield_plugin
    ros2_initial_plugins:
      - /guidance/plugins/inlanecruising_plugin
      - /guidance/plugins/platoon_strategic_ihp_node
      - /guidance/plugins/stop_and_wait_plugin
      - /guidance/plugins/route_following_plugin
      - /guidance/plugins/platooning_tactical_plugin_node
      - /guidance/plugins/cooperative_lanechange
      - /guidance/plugins/light_controlled_intersection_tactical_plugin
      - /guidance/plugins/sci_strategic_plugin
      - /guidance/plugins/stop_controlled_intersection_tactical_plugin
      - /guidance/plugins/yield_plugin
      - /guidance/plugins/pure_pursuit_wrapper
      - /guidance/plugins/lci_strategic_plugin
      - /guidance/plugins/intersection_transit_maneuvering
