/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 2000

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 10000

    subsystem_namespace: /localization
    required_subsystem_nodes: ['']
    unmanaged_required_nodes: ['']
    full_subsystem_required: true
    sensor_nodes:
      - /hardware_interface/velodyne_lidar_driver_wrapper_node
    # TODO update the fault map once ros2 gps is integrated
    sensor_fault_map: '
      {
        "sensor_fault_map":
        [
          [0,0]
        ]
      }
      '

