/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 2000

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 10000

    subsystem_namespace: /message
    required_subsystem_nodes: ['']
    unmanaged_required_nodes:
      - /hardware_interface/dsrc_driver_node
    full_subsystem_required: true