name: Docker Hub build
# This workflow will build and push of docker images when new push occurs to develop, master, release branches but doesn't run any unit test or sonar scanner
on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"

jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
