name: Docker build
# This workflow will only build for Pullrequest which are opened, changed , merged 
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
